ci:
  skip: [ty-check]

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.8
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/astral-sh/ty-pre-commit
  rev: v0.0.80
  hooks:
    - id: ty

- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
      name: cargo fmt
    - id: cargo-check
