class Curve:
    def __init__(self, name: str, p: int, a: int, b: int, q: int, gx: int, gy: int): ...
    @staticmethod
    def p192() -> Curve: ...
    @staticmethod
    def p224() -> Curve: ...
    @staticmethod
    def p256() -> Curve: ...
    @staticmethod
    def p384() -> Curve: ...
    @staticmethod
    def p521() -> Curve: ...
    @staticmethod
    def secp256k1() -> Curve: ...
    @property
    def p(self) -> int: ...
    @property
    def a(self) -> int: ...
    @property
    def b(self) -> int: ...
    @property
    def q(self) -> int: ...
    @property
    def G(self) -> Point: ...
    @property
    def oid(self) -> bytes: ...
    def sign(self, msg: bytes, d: bytes, k: bytes) -> tuple[bytes, bytes]: ...
    def verify(self, r: bytes, s: bytes, msg: bytes, qx: bytes, qy: bytes) -> bool: ...
    def is_point_on_curve(self, point: Point) -> bool: ...
    def evaluate(self, x: int) -> int: ...
    def __repr__(self) -> str: ...

class Point:
    def __init__(self, x: int, y: int, curve: Curve) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def curve(self) -> Curve: ...
    def __add__(self, other: Point) -> Point: ...
    def __mul__(self, scalar: int) -> Point: ...
    def __rmul__(self, scalar: int) -> Point: ...
    def __neg__(self) -> Point: ...
    def __sub__(self, other: Point) -> Point: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
