class Curve:
    @staticmethod
    def p192() -> Curve: ...
    @staticmethod
    def p224() -> Curve: ...
    @staticmethod
    def p256() -> Curve: ...
    @staticmethod
    def p384() -> Curve: ...
    @staticmethod
    def p521() -> Curve: ...
    @property
    def q(self) -> int: ...
    def sign(self, msg: bytes, d: bytes, k: bytes) -> tuple[bytes, bytes]: ...
    def verify(self, r: bytes, s: bytes, msg: bytes, qx: bytes, qy: bytes) -> bool: ...
    def __repr__(self) -> str: ...
