def p192_sign(msg: bytes, d_bytes: bytes, k_bytes: bytes) -> tuple[bytes, bytes]: ...
def p192_verify(
    r_bytes: bytes, s_bytes: bytes, msg: bytes, qx_bytes: bytes, qy_bytes: bytes
) -> bool: ...
def p224_sign(msg: bytes, d_bytes: bytes, k_bytes: bytes) -> tuple[bytes, bytes]: ...
def p224_verify(
    r_bytes: bytes, s_bytes: bytes, msg: bytes, qx_bytes: bytes, qy_bytes: bytes
) -> bool: ...
def p256_sign(msg: bytes, d_bytes: bytes, k_bytes: bytes) -> tuple[bytes, bytes]: ...
def p256_verify(
    r_bytes: bytes, s_bytes: bytes, msg: bytes, qx_bytes: bytes, qy_bytes: bytes
) -> bool: ...
def p384_sign(msg: bytes, d_bytes: bytes, k_bytes: bytes) -> tuple[bytes, bytes]: ...
def p384_verify(
    r_bytes: bytes, s_bytes: bytes, msg: bytes, qx_bytes: bytes, qy_bytes: bytes
) -> bool: ...
def p521_sign(msg: bytes, d_bytes: bytes, k_bytes: bytes) -> tuple[bytes, bytes]: ...
def p521_verify(
    r_bytes: bytes, s_bytes: bytes, msg: bytes, qx_bytes: bytes, qy_bytes: bytes
) -> bool: ...
