name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v3

      - name: Cache vcpkg
        uses: actions/cache@v3
        id: cache-vcpkg
        with:
          path: ${{ github.workspace }}/vcpkg
          key: ${{ runner.os }}-build-${{ env.cache-name }}-gmp
        if: matrix.os == 'windows-2019'

      - name: clone and bootstrap vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%"
          IF NOT EXIST "vcpkg" (
              git clone https://github.com/microsoft/vcpkg
              cd "vcpkg"
              git reset --hard 2022.11.14
              .\bootstrap-vcpkg.bat
          )
        shell: cmd
        if: matrix.os == 'windows-2019'

      - name: Install dependencies with vcpkg
        run: |
          cd "%GITHUB_WORKSPACE%\vcpkg"
          IF NOT EXIST "buildtrees\gmp" (
              .\vcpkg --version
              .\vcpkg install gmp:x64-windows gmp:x86-windows
          )
        shell: cmd
        if: matrix.os == 'windows-2019'

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_ENVIRONMENT_WINDOWS: >
            INCLUDE="$GITHUB_WORKSPACE/vcpkg/installed/x64-windows/include/;$INCLUDE"
            LIB="$GITHUB_WORKSPACE/vcpkg/installed/x64-windows/lib/;$GITHUB_WORKSPACE/vcpkg/installed/x86-windows/lib/;$LIB"
          CIBW_BEFORE_BUILD: ls "$GITHUB_WORKSPACE/vcpkg/installed/x64-windows/lib/"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
